name: kyahaal
description: A new Flutter project.
publish_to: "none"
version: 1.1.7+8
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.10.24
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  get: ^4.3.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  simpler_login: ^0.0.1+8

dev_dependencies:
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
